name: Execute Main Script

on:
  push:
    branches: [ main, master ]

jobs:
  execute_main:
    runs-on: ubuntu-latest
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Python環境のセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 依存関係をインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: main.py の実行
      run: python main.py > result.txt

    - name: 結果を表示
      run: cat result.txt
