name: Execute Main Script

on:
  push:
    branches: [ main, master ]

jobs:
  execute_main:
    runs-on: ubuntu-latest
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Python環境のセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: mlflowのインストール
      run: 
        pip install mlflow

    - name: main.py の実行
      run: python day5/演習1/main.py result.txt | tee compare.txt result.txt

    - name: 生成されたファイルを保存
      uses: actions/upload-artifact@v4
      with:
        name: generated-files
        path: |
          result.txt
          compare.txt
        

    - name: アーティファクトを表示
      run: cat result.txt compare.txt
      
